version: '3.8'

services:
  node0:
    build:
      context: .
      args:
        ID: 0
    container_name: tendermint_node0
    depends_on:
      - abci0
    ports:
      - "26656:26656"
      - "26657:26657"
    volumes:
      - ./node0:/tendermint
    environment:
      - ID=0
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    build:
      context: .
      args:
        ID: 1
    container_name: tendermint_node1
    depends_on:
      - abci1
    ports:
      - "26658:26656"
      - "26659:26657"
    volumes:
      - ./node1:/tendermint
    environment:
      - ID=1
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    build:
      context: .
      args:
        ID: 2
    container_name: tendermint_node2
    depends_on:
      - abci2
    ports:
      - "26660:26656"
      - "26661:26657"
    volumes:
      - ./node2:/tendermint
    environment:
      - ID=2
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    build:
      context: .
      args:
        ID: 3
    container_name: tendermint_node3
    depends_on:
      - abci3
    ports:
      - "26662:26656"
      - "26663:26657"
    volumes:
      - ./node3:/tendermint
    environment:
      - ID=3
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  abci0:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci0
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci1
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci2
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci3
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.10.0/24
