version: '3.8'

services:

  node0:
    image: tendermint/tendermint:latest
    container_name: tendermint_node0
    depends_on:
      - abci0
    volumes:
      - "./node0:/tendermint"
    networks:
      localnet:
        ipv4_address: 192.167.10.2
    ports:
      - "26656-26657:26656-26657"
    command:
      - node

  node1:
    image: tendermint/tendermint:latest
    container_name: tendermint_node1
    depends_on:
      - abci1
    volumes:
      - "./node1:/tendermint"
    networks:
      localnet:
        ipv4_address: 192.167.10.3
    ports:
      - "26658-26659:26656-26657"
    command:
      - node

  node2:
    image: tendermint/tendermint:latest
    container_name: tendermint_node2
    depends_on:
      - abci2
    volumes:
      - "./node2:/tendermint"
    networks:
      localnet:
        ipv4_address: 192.167.10.4
    ports:
      - "26660-26661:26656-26657"
    command:
      - node

  node3:
    image: tendermint/tendermint:latest
    container_name: tendermint_node3
    depends_on:
      - abci3
    volumes:
      - "./node3:/tendermint"
    networks:
      localnet:
        ipv4_address: 192.167.10.5
    ports:
      - "26662-26663:26656-26657"
    command:
      - node

  abci0:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci0
    volumes:
      - ./abci0:/app/db
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci1
    volumes:
      - ./abci1:/app/db
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci2
    volumes:
      - ./abci2:/app/db
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    build:
      context: ./js-abci
      dockerfile: Dockerfile
    container_name: abci3
    volumes:
      - ./abci3:/app/db
    tty: true
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.10.0/24
