version: '3.8'

services:
  node0:
    container_name: node0
    image: "tendermint/localnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.2
  node1:
    container_name: node1
    image: "tendermint/localnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.3
  node2:
    container_name: node2
    image: "tendermint/localnode"
    ports:
      - "26662-26663:26656-26657"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.4
  node3:
    container_name: node3
    image: "tendermint/localnode"
    ports:
      - "26665-26666:26656-26657"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.5
  node4:
    container_name: node4
    image: "tendermint/localnode"
    ports:
      - "26668-26669:26656-26657"
    environment:
      - ID=4
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.6

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.0.0/16
